// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWTexture2D<float4> LutTex;
RWBuffer<int> Size;

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    float exponent = 2 * 3.1415926 * id.x / Size[0];
    //欧拉恒等式
    float real = cos(exponent);
    float ima = sin(exponent);
    LutTex[id.xy] = float4(real, 0, ima, 1);
}
